name: Update Profile README

on:
  workflow_dispatch:
  schedule:
    - cron: "17 0 * * *" # 毎日09:17(JST)頃

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout profile repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          pip install requests python-dateutil

      - name: Generate sections & SVG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_USER: ${{ github.repository_owner }}
        run: |
          python scripts/update_readme.py

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md assets/monthly_activity.svg
          git diff --staged --quiet || git commit -m "chore: auto-update README sections"
          git push
